# Generated by Django 2.2.4 on 2019-09-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porject',
            new_name='Project',
        ),
    ]
